"""Initial immutable schema and deferred expense balance constraints."""

from alembic import op
import sqlalchemy as sa

revision = "001"
down_revision = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=300), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("opening_balance", sa.BigInteger(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind in ('checking','cash','savings')"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_household_id"), "accounts", ["household_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_household_id"), "audit_events", ["household_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("group", sa.String(length=40), nullable=False),
        sa.Column("icon", sa.String(length=30), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name"),
    )
    op.create_index(op.f("ix_categories_household_id"), "categories", ["household_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("target", sa.BigInteger(), nullable=False),
        sa.Column("opening_amount", sa.BigInteger(), nullable=False),
        sa.Column("monthly_amount", sa.BigInteger(), nullable=False),
        sa.Column("icon", sa.String(length=30), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("target > 0 and opening_amount >= 0 and monthly_amount >= 0"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_household_id"), "goals", ["household_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by", sa.String(length=36), nullable=True),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_invitations_household_id"), "invitations", ["household_id"], unique=False)
    op.create_table(
        "members",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("role in ('owner','member')"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "user_id"),
    )
    op.create_index(op.f("ix_members_household_id"), "members", ["household_id"], unique=False)
    op.create_table(
        "merchants",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name"),
    )
    op.create_index(op.f("ix_merchants_household_id"), "merchants", ["household_id"], unique=False)
    op.create_table(
        "periods",
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("planned_income", sa.BigInteger(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("planned_income >= 0"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "month"),
    )
    op.create_index(op.f("ix_periods_household_id"), "periods", ["household_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "budget_allocations",
        sa.Column("period_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("reference_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("group", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind in ('category','pocket','goal')"),
        sa.CheckConstraint("amount >= 0"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["period_id"], ["periods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("period_id", "kind", "reference_id"),
    )
    op.create_index(op.f("ix_budget_allocations_household_id"), "budget_allocations", ["household_id"], unique=False)
    op.create_index(op.f("ix_budget_allocations_period_id"), "budget_allocations", ["period_id"], unique=False)
    op.create_table(
        "classification_rules",
        sa.Column("pattern", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind in ('exact','normalized','merchant')"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "kind", "pattern"),
    )
    op.create_index(op.f("ix_classification_rules_household_id"), "classification_rules", ["household_id"], unique=False)
    op.create_table(
        "recurring",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("amount > 0 and day between 1 and 31"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recurring_household_id"), "recurring", ["household_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=160), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=True),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("goal_id", sa.String(length=36), nullable=True),
        sa.Column("merchant_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind != 'pocket' or member_id is not null"),
        sa.CheckConstraint("kind != 'saving' or (goal_id is not null and destination_id is not null)"),
        sa.CheckConstraint("kind != 'transfer' or destination_id is not null"),
        sa.CheckConstraint("kind in ('expense','income','pocket','transfer','saving')"),
        sa.CheckConstraint("status in ('categorized','unallocated')"),
        sa.CheckConstraint("amount > 0"),
        sa.CheckConstraint("destination_id is null or destination_id != account_id"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "idempotency_key"),
    )
    op.create_index(op.f("ix_transactions_household_id"), "transactions", ["household_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("merchant", sa.String(length=120), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("total", sa.BigInteger(), nullable=True),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("transaction_id", sa.String(length=36), nullable=True),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("status in ('draft','ready','confirmed','failed')"),
        sa.CheckConstraint("total is null or total > 0"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index(op.f("ix_receipts_household_id"), "receipts", ["household_id"], unique=False)
    op.create_index(op.f("ix_receipts_image_hash"), "receipts", ["image_hash"], unique=False)
    op.create_table(
        "transaction_allocations",
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id", "category_id"),
    )
    op.create_index(op.f("ix_transaction_allocations_household_id"), "transaction_allocations", ["household_id"], unique=False)
    op.create_index(op.f("ix_transaction_allocations_transaction_id"), "transaction_allocations", ["transaction_id"], unique=False)
    op.create_table(
        "receipt_items",
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("quantity", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("amount > 0 and confidence between 0 and 100"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipt_items_household_id"), "receipt_items", ["household_id"], unique=False)
    op.create_index(op.f("ix_receipt_items_receipt_id"), "receipt_items", ["receipt_id"], unique=False)
    op.create_table(
        "review_tasks",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=True),
        sa.Column("transaction_id", sa.String(length=36), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("household_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind in ('classification','extraction','duplicate','unallocated')"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_tasks_household_id"), "review_tasks", ["household_id"], unique=False)
    # ### end Alembic commands ###
    op.execute("""
    CREATE FUNCTION check_transaction_balance() RETURNS trigger AS $$
    DECLARE tid varchar; tx_kind varchar; tx_status varchar; tx_amount bigint; total bigint;
    BEGIN
      IF TG_TABLE_NAME = 'transactions' THEN
        IF TG_OP = 'DELETE' THEN tid := OLD.id; ELSE tid := NEW.id; END IF;
      ELSE
        IF TG_OP = 'DELETE' THEN tid := OLD.transaction_id; ELSE tid := NEW.transaction_id; END IF;
      END IF;
      SELECT kind, status, amount INTO tx_kind, tx_status, tx_amount FROM transactions WHERE id = tid;
      IF tx_kind = 'expense' AND tx_status = 'categorized' THEN
        SELECT coalesce(sum(amount),0) INTO total FROM transaction_allocations WHERE transaction_id = tid;
        IF total != tx_amount THEN RAISE EXCEPTION 'Allocation total does not equal transaction amount' USING ERRCODE = '23514'; END IF;
      END IF;
      RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    CREATE CONSTRAINT TRIGGER transaction_balance AFTER INSERT OR UPDATE ON transactions
      DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_transaction_balance();
    CREATE CONSTRAINT TRIGGER allocation_balance AFTER INSERT OR UPDATE OR DELETE ON transaction_allocations
      DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_transaction_balance();
    """)


def downgrade():
    op.execute("DROP FUNCTION check_transaction_balance() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_tasks_household_id"), table_name="review_tasks")
    op.drop_table("review_tasks")
    op.drop_index(op.f("ix_receipt_items_receipt_id"), table_name="receipt_items")
    op.drop_index(op.f("ix_receipt_items_household_id"), table_name="receipt_items")
    op.drop_table("receipt_items")
    op.drop_index(op.f("ix_transaction_allocations_transaction_id"), table_name="transaction_allocations")
    op.drop_index(op.f("ix_transaction_allocations_household_id"), table_name="transaction_allocations")
    op.drop_table("transaction_allocations")
    op.drop_index(op.f("ix_receipts_image_hash"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_household_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_transactions_household_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_recurring_household_id"), table_name="recurring")
    op.drop_table("recurring")
    op.drop_index(op.f("ix_classification_rules_household_id"), table_name="classification_rules")
    op.drop_table("classification_rules")
    op.drop_index(op.f("ix_budget_allocations_period_id"), table_name="budget_allocations")
    op.drop_index(op.f("ix_budget_allocations_household_id"), table_name="budget_allocations")
    op.drop_table("budget_allocations")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_periods_household_id"), table_name="periods")
    op.drop_table("periods")
    op.drop_index(op.f("ix_merchants_household_id"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_members_household_id"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_invitations_household_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_goals_household_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_categories_household_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_audit_events_household_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_accounts_household_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("households")
    # ### end Alembic commands ###
